---
site_name: Ultirepo

nav:
- index.md
- How-To:
    - how-to/index.md
- Examples:
    - "!include https://github.com/emil-jacero/repo1.git?ref=main&nav_path=docs/include_bang/nav.yml"

plugins:
- search
- ultirepo

theme:
    name: material
