---
site_name: Dogs API

nav:
- How-To Guides:
    - "!include https://github.com/emil-jacero/repo2.git?ref=main&nav_path=docs/how-to-guides/nav.yml"

plugins:
- search
- ultirepo

theme:
    name: material
