---
site_name: Dogs API

nav:
- index.md
- How-To Guides:
    - how-to-guides/index.md
    - how-to-guides/guide-1.md
    - "!include https://github.com/emil-jacero/repo2.git?ref=main&nav_path=docs/how-to-guides/nav.yml"
- System-Documentation: system-documentation/index.md

plugins:
- search
- ultirepo

theme:
    name: material
